@baseUrl = http://localhost:3005

GET {{baseUrl}}/dept/lectures

###
GET {{baseUrl}}/cls/classes

###
GET {{baseUrl}}/cls/generate

###
GET {{baseUrl}}/bat/batchsubjects/?course_id=1

###
DELETE {{baseUrl}}/dept/delete-department/?departmentId=14

###
GET {{baseUrl}}/dept/departments

###
GET {{baseUrl}}/dept/get-department/?departmentId=3

###
POST {{baseUrl}}/sub/subjects
Content-Type: application/json

{
   "department_id":11,
  "course_name":"BSC EEE"
}

###
PUT {{baseUrl}}/dept/update-department/?departmentId=12
Content-Type: application/json

{
 
"department_name":"Information Science Technology"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
"username":"admin1",
"password":"admin1_password"
}

###
POST {{baseUrl}}/auth/create-account
Content-Type: application/json

{
  "institution_id": 1,
  "username": "admin1",
  "email": "admin1@school.com",
  "password": "admin1_password",
  "user_type": "Admin"
}

@onboarding = {{baseUrl}}/onboarding

### Get institution types
GET {{onboarding}}/institution-types

### Check institution code availability
GET {{onboarding}}/check-code/UNI

### Create institution + admin
POST {{onboarding}}/register
Content-Type: application/json

{
  "institution_code": "ABC",
  "institution_name": "ABC Technical Institute",
  "institution_type": "Technical",
  "address": "Nairobi, Kenya",
  "phone": "+254700000000",
  "email": "info@abc.ac.ke",

  "admin_username": "superadmin",
  "admin_email": "admin@abc.ac.ke",
  "admin_password": "StrongPass123"
}